<?php echo $this->docType(); ?>

<html dir="ltr">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle('applicationTitle')->setSeparator(' - '); ?>

        <?php echo $this->headMeta(); ?>

        <?php echo $this->headLink(); ?>

        <?php echo $this->headScript(); ?>

        <?php echo $this->headStyle(); ?>

    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>
