<?php

$this->authenticateForm->setAttribute('action', $this->url('login'));
$this->authenticateForm->setAttribute('method', 'post');
$this->authenticateForm->prepare();

?>
<?php echo $this->form()->openTag($this->authenticateForm); ?>

<?php echo $this->formHidden($this->authenticateForm->get('authentication')); ?>
<?php echo $this->formElementErrors($this->authenticateForm->get('authentication')); ?>

<?php if ($this->authenticateForm->has('profile')) { ?>
<p>
    <?php echo $this->formLabel($this->authenticateForm->get('profile')); ?>
    <?php echo $this->formSelect($this->authenticateForm->get('profile')); ?>
    <?php echo $this->formElementErrors($this->authenticateForm->get('profile')); ?>
</p>
<?php } ?>

<p>
    <?php echo $this->formLabel($this->authenticateForm->get('identity')); ?>
    <?php echo $this->formText($this->authenticateForm->get('identity')); ?>
    <?php echo $this->formElementErrors($this->authenticateForm->get('identity')); ?>
</p>

<p>
    <?php echo $this->formLabel($this->authenticateForm->get('credential')); ?>
    <?php echo $this->formPassword($this->authenticateForm->get('credential')); ?>
    <?php echo $this->formElementErrors($this->authenticateForm->get('credential')); ?>
</p>

<p>
    <?php echo $this->formSubmit($this->authenticateForm->get('submit')); ?>
</p>

<?php echo $this->form()->closeTag(); ?>
